### ISSUE TITLE
docker-compose.yml default mounts local copy of code into containers

### ISSUE THREAD

**Issue by tstescoTT** [tenstorrent/tt-studio#84]
If for example one builds a version of the frontend then the `node_modules` will be stored on the host and will clobber when a container is built using `docker compose up --build` on the second run.

Mounting the local source code are development features and not expected for deployment default.

https://github.com/tenstorrent/tt-studio/blob/main/app/docker-compose.yml#L49
```yml
...
    volumes:
      # mounting docker unix socket allows for backend container to run docker cmds
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOST_PERSISTENT_STORAGE_VOLUME}:${INTERNAL_PERSISTENT_STORAGE_VOLUME}
      # for development mount api changes
      - ./api:/api

  tt_studio_frontend:
    container_name: tt_studio_frontend
    hostname: tt-studio-frontend
    image: ghcr.io/tenstorrent/tt-studio/frontend:v0.0.0
    build: ./frontend
    networks: 
      - llm_studio_network
    ports:
      - "3000:3000"
    volumes:
      # for development mount api changes
      - ./frontend:/frontend
    # command: sh
    command: bash -c "npm i && npm run dev"
```
